Created new Genre page
Team-Harbinger/Harbinger-Musik pull request #30
Opened 2021-08-01 04:00 UTC by roundband5

New Genre page with top 20 songs playlist

![ezgif-6-270c9efa5e0d](https://user-images.githubusercontent.com/30790329/127758732-8ef3c309-8b64-4cee-b78b-0845c4d75215.gif)

2021-08-01 09:30 UTC, leonzh2k commented on src/modules/Genre/Genre.css
> +  .image-col{
Fix spacing (one space between selector and bracket)

2021-08-01 09:31 UTC, leonzh2k commented on src/modules/Genre/Genre.css
> +    font-size:1.5em;
Fix spacing

2021-08-01 09:32 UTC, leonzh2k commented on src/modules/Genre/Genre.css
> +    font-size:800%;
Spacing

2021-08-01 09:33 UTC, leonzh2k requested changes
Looks good except for inconsistent spacing.

2021-08-02 23:42 UTC, lchua2314 approved these changes
Make leonzh2k changes then it's good.

2021-08-04 01:30 UTC, roundband5 commented
Fixed spacing issues in code
improved website readability

2021-08-04 03:13 UTC, leonzh2k approved these changes
Looks good, merging

2021-08-04 03:13 UTC, merged